[workspace]
authors = ["Jeongseok Lee <jslee02@gmail.com>"]
channels = ["conda-forge"]
name = "srlib"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
cmake = ">=4.2.1,<5"
glew = ">=2.2.0,<3"
ninja = ">=1.13.2,<2"
openscenegraph = ">=3.6.5,<4"

[target.linux-64.dependencies]
freeglut = ">=3.2.2,<4"
libglu = ">=9.0.3,<10"
libgl-devel = ">=1.7,<2"

[target.win-64.dependencies]
freeglut = ">=3.2.2,<4"

[tasks]

[tasks.configure]
cmd = "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DSRLIB_ENABLE_OSG=ON"

[tasks.build]
cmd = "cmake --build build"
depends-on = ["configure"]

[tasks.clean]
cmd = "cmake --build build --target clean"
depends-on = ["configure"]
